site_name: Lucas Brown TD
site_description: Lucas Brown - Technical Director
copyright: 2023 Lucas Brown

nav:
    - Home: index.md
    - Projects: projects.md
    - Resume: resume.md
    - About: about.md

markdown_extensions:
  - admonition

theme:
  name: null
  custom_dir: 'cinder'
  colorscheme: dracula
