site_name: Lucas Brown TD
site_description: Lucas Brown TD
copyright: 2020 Lucas Brown

nav:
    - Home: index.md
    - Projects: projects.md
    - Resume: resume.md
    - About: about.md

markdown_extensions:
  - admonition

theme:
  name: material
  highlightjs: true
  hljs_style: tomorrow-night
      - python
