site_name: Lucas Brown | Scalable 3D Pipelines & Tools
site_description: Specializing in 3D content automation, creative tooling, practical AI, and cross-team systems.
copyright: 2025 Lucas Brown

nav:
    - Home: index.md
    - Projects: projects.md
    - Resume: resume.md
    - About: about.md

markdown_extensions:
  - admonition

theme:
  name: null
  custom_dir: 'cinder'
  colorscheme: dracula
